### ISSUE TITLE
Why the input dimension of bbox is 6 ? 

### ISSUE THREAD

**Issue by Fly2flies** [ajseo95/MASN-pytorch#3]
Thank you for sharing such a great codebase !
But I have a puzzle. Detection box is usually represented as 4 dimensions, (x,y,w,h) or (x1,y1,x2,y2). 
Why is the input dimension of  `bbox_location_encoding = nn.Linear(6, 64)`  is 6 ?

**Comment by jeyajseo** [comment]
Hi. Thank you for having an interest in our work.:) We add scaled width and scaled height into the 4 dimensions. We just add a python file and you can refer to adaptive_detection_features_converter.py. Also, you can download extracted feature hdf5 file in README.

**Comment by Fly2flies** [comment]
Thanks for your reply. 
I was wondering if it would be convenient for you to split [tGIF_i3d_roiALIGN_hw7_perclip_avgpool.hdf5](https://drive.google.com/file/d/1JbHWs0yTExL7Lc_abCvaXX49IsazUVvw/view?usp=sharing) into several small segments ?
It might be easier to download!

**Comment by staceycy** [comment]
> Thanks for your reply.
> I was wondering if it would be convenient for you to split [tGIF_i3d_roiALIGN_hw7_perclip_avgpool.hdf5](https://drive.google.com/file/d/1JbHWs0yTExL7Lc_abCvaXX49IsazUVvw/view?usp=sharing) into several small segments ?
> It might be easier to download!

Hi, 

May I know if you have succeeded in downloading the file mentioned above? I also have problem in downloading it. 

Thank you and looking forward to your reply.
